% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother


% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}



\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{tabularray}
\usepackage[normalem]{ulem}
\usepackage{graphicx}
\usepackage{rotating}
\UseTblrLibrary{booktabs}
\UseTblrLibrary{siunitx}
\NewTableCommand{\tinytableDefineColor}[3]{\definecolor{#1}{#2}{#3}}
\newcommand{\tinytableTabularrayUnderline}[1]{\underline{#1}}
\newcommand{\tinytableTabularrayStrikeout}[1]{\sout{#1}}
\usepackage{url}
\urlstyle{same}
\def\UrlBreaks{\do/\do-\do.\do:}
\usepackage{float}
\usepackage{array}
\usepackage{siunitx}
\usepackage{dcolumn}
\usepackage{tikz}
\newcolumntype{d}[1]{D{.}{.}{#1}}
% reset numbering after abstract
\usepackage{etoolbox}
\AtBeginEnvironment{abstract}{\setcounter{section}{0}}
% Custom table row spacing
\renewcommand{\arraystretch}{0.9}
% Configure siunitx for modern versions (>=3)
\sisetup{
  detect-all,
  input-symbols = (),
  input-signs = + -,
  table-align-text-pre = false,
  table-number-alignment = center,
  table-format = +1.4,
  group-digits = false,
  table-space-text-pre = ***,
  table-space-text-post = ***,
  mode = math
}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Denominator Contamination in a Vacancy-Based Tightness Measure},
  pdfauthor={Jacob Khaykin; David Kane},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Denominator Contamination in a Vacancy-Based Tightness Measure}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{A Replication and Reanalysis of Andreadis et al.~(AEA Papers
and Proceedings, 2025)}
\author{Jacob Khaykin\footnote{Solon High School,
  jacobkhaykin27@solonschools.net} \and David Kane\footnote{New College
  of Florida, dakane@ncf.edu}}
\date{}
\begin{document}
\maketitle


\emph{JEL: J24, O33, R11, C13}

\emph{Keywords:} Artificial Intelligence, Regional Economics, Labor
Markets

\emph{Data Availability:} The R code and data to reproduce this
replication are available in this repository.\footnote{https://github.com/JacobKhay/Andreadis-Replication}

\section*{Abstract}\label{abstract}
\addcontentsline{toc}{section}{Abstract}

We identify denominator contamination in Andreadis et al.~(2025)'s key
labor-market tightness variable: total job postings appear in both the
AI-intensity denominator and the tightness numerator. Denominator
contamination occurs when a constructed regressor shares a numerator or
denominator component with the dependent variable, creating mechanical
correlation. In a calibrated simulation designed to mirror the panel's
dispersion, the contaminated specification produces a nonzero
coefficient even when the AI rate is generated independently of
unemployment. In the empirical reanalysis, the tightness coefficient is
not separately identifiable from postings scale: once postings scale is
separated from unemployment using decomposition or an offset-count
model, the tightness signal largely disappears. We also compare
alternative weighting schemes after removing tightness to assess
sensitivity to the estimand. Our reanalysis indicates the associations
are more modest than originally presented.

Declaration: There are no financial conflicts of interest to share.
\newpage

\section{Introduction}\label{introduction}

Artificial intelligence is reshaping labor demand and the geography of
high-skill work, with county-level variation that matters for regional
policy. Andreadis et al.~(2025) provide one of the first systematic
county-level accounts of AI job posting intensity and its growth over
time, motivating place-based strategies and regional diagnostics.

Their headline results emphasize labor-market tightness and education.
In the levels specification, tightness and bachelor's share are the
largest positive correlates of AI job intensity. In the growth
specification, STEM degree share and tightness are the strongest
positive correlates. These patterns have been cited as evidence that AI
posting intensity tends to be higher in counties with tighter labor
markets and higher education.

However, the labor-market tightness variable suffers from denominator
contamination (\citeproc{ref-kronmal1993spurious}{Kronmal, 1993};
\citeproc{ref-wooldridge2005}{Wooldridge, 2005}). Total postings appear
in the denominator of AI intensity and the numerator of tightness,
inducing mechanical correlation even under independence between AI
postings and unemployment. As a result, the tightness coefficient partly
reflects shared arithmetic structure rather than a purely economic
relationship; because tightness is correlated with other covariates, its
inclusion may also affect the remaining estimates.

We reproduce Tables 1 and 2, demonstrate the mechanical component using
a DAG, a simple example, and a simulation, and then re-estimate the main
specifications without the contaminated tightness variable. As a
secondary check, we compare alternative weighting schemes (including
log-population weights) after removing tightness to assess sensitivity
to the estimand. This is not a critique of tightness as a concept, but
of using a tightness measure that reuses the dependent variable's
denominator, which mechanically inflates partial correlations.

\section{Data}\label{data}

AKCLM combine Lightcast postings data with county-level demographics
from the American Community Survey, innovation measures from patents and
STEM degree shares, industry composition from CBP and QWI, and house
price growth. All explanatory variables are lagged by one year. The main
outcome is AI job intensity, and the growth outcome is the change in AI
intensity between pooled 2017-2018 and 2022-2023 averages.

The key variables are defined as follows. The AI intensity outcome is:
\[AI_{it} = \frac{\text{AI job postings}_{it}}{\text{Total job postings}_{it}} \times 100 \tag{1}\]
The tightness variable is:
\[Tightness_{it} = \frac{\text{Total postings}_{it}}{\text{Unemployed}_{it}} \tag{2}\]

Consider a library that reports the share of sci-fi books borrowed
(sci-fi/total) and a ``busyness'' measure defined as total books
borrowed divided by overdue books. Even if sci-fi borrowing is unrelated
to overdue books, the shared total-borrowed term mechanically links the
two ratios. The same arithmetic applies here: AI intensity divides by
total postings while tightness multiplies by total postings.

This shared component can induce a mechanical correlation. Even if AI
postings are generated independently of unemployment conditional on
total postings, the shared total-postings term can generate nontrivial
partial correlation between A/T and T/U once sampling noise and ratio
variation interact with T. This is not universal (e.g., if A = pT with p
independent, then A/T = p), so the magnitude and sign depend on the
data-generating process. The corresponding construction diagram is:

\begin{figure}[H]

\caption{\label{fig-dag}Construction diagram for denominator
contamination}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{replication_files/figure-pdf/fig-dag-1.pdf}}

}

\end{figure}%

\section{Replication}\label{replication}

We reproduce Tables 1 and 2 using the authors' data.csv. Most
coefficients and standard errors match the published tables exactly; one
coefficient in Table 2 differs slightly, which likely reflects an
undocumented preprocessing or default-setting difference. The
denominator-contamination results do not depend on that discrepancy. The
replication tables use the authors' provided \texttt{data.csv}; Figure 1
uses an updated Lightcast extraction
(\texttt{updated\_lightcast\_county.csv}) and Census shapefiles via
\texttt{tigris} to reproduce the spatial visualization and is not
required for the table replication. Connecticut has no county
observations in the provided dataset, so it is shown as no data.

\begin{table}[H]

\caption{\label{tbl-table1}Replication of Table 1 from Andreadis et
al.~(2025) - The Correlates of the Share of Artificial Intelligence
Jobs}

\centering{

\centering
\begin{talltblr}[         %% tabularray outer open
entry=none,label=none,
note{}={This table examines the demographic, innovation, and industry determinants of the share of artificial intelligence jobs across U.S. counties from 2014 to 2023. The dependent variable is AI job intensity, defined as the ratio of AI job postings to total job postings in each county-year, multiplied by 100 to express in percentage terms. AI job postings are identified from Lightcast data using skills and keywords associated with artificial intelligence. All explanatory variables are standardized as z-scores to ensure comparability across predictors. The sample comprises county-year observations covering approximately 3,100 U.S. counties annually over the ten-year period. All coefficients represent percentage point changes in AI job share for a one standard deviation increase in the explanatory variable. Models are estimated using ordinary least squares with county and year fixed effects (columns 1-4) or county and state-year fixed effects (column 5). Standard errors are clustered at the county level. All explanatory variables are lagged by one year.},
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]Q[]Q[]Q[]Q[]},
column{2}={si={table-format=-1.6,table-align-text-before=false,table-align-text-after=false,input-symbols={-,\*+()}},},
cell{1}{2}={guard,halign=c,},
column{3}={si={table-format=-1.6,table-align-text-before=false,table-align-text-after=false,input-symbols={-,\*+()}},},
cell{1}{3}={guard,halign=c,},
column{4}={si={table-format=-1.6,table-align-text-before=false,table-align-text-after=false,input-symbols={-,\*+()}},},
cell{1}{4}={guard,halign=c,},
column{5}={si={table-format=-1.6,table-align-text-before=false,table-align-text-after=false,input-symbols={-,\*+()}},},
cell{1}{5}={guard,halign=c,},
column{6}={si={table-format=-1.6,table-align-text-before=false,table-align-text-after=false,input-symbols={-,\*+()}},},
cell{1}{6}={guard,halign=c,},
column{1}={}{halign=l,},
}                     %% tabularray inner close
\toprule
& (1) & (2) & (3) & (4) & (5) \\ \midrule %% TinyTableHeader
Bachelor's share & 0.1906 &  &  & 0.1817 & 0.1035 \\
& (0.0513) &  &  & (0.0505) & (0.0459) \\
House price growth & -0.0144 &  &  & -0.0142 & -0.0156 \\
& (0.0080) &  &  & (0.0079) & (0.0074) \\
Labor tightness & 0.2780 &  &  & 0.2765 & 0.3156 \\
& (0.0583) &  &  & (0.0585) & (0.0643) \\
Patents per employee &  & 0.0232 &  & 0.0295 & 0.0312 \\
&  & (0.0091) &  & (0.0113) & (0.0138) \\
STEM degrees share &  & 0.0686 &  & 0.0475 & 0.0375 \\
&  & (0.0238) &  & (0.0205) & (0.0184) \\
ICT sector intensity &  &  & 0.0121 & 0.0258 & 0.0280 \\
&  &  & (0.0144) & (0.0135) & (0.0136) \\
Manufacturing &  &  & -0.0630 & -0.0333 & -0.0247 \\
&  &  & (0.0113) & (0.0108) & (0.0111) \\
Turnover rate &  &  & 0.0345 & 0.0188 & 0.0154 \\
&  &  & (0.0137) & (0.0137) & (0.0132) \\
Fixed effects & {\hspace{0.5em}County, Year} & {\hspace{0.5em}County, Year} & {\hspace{0.5em}County, Year} & {\hspace{0.5em}County, Year} & {\hspace{0.5em}County, state-year} \\
Observations & {\hspace{0.5em}24,645} & {\hspace{0.5em}24,645} & {\hspace{0.5em}24,645} & {\hspace{0.5em}24,645} & {\hspace{0.5em}24,645} \\
R² & {\hspace{0.5em}0.69739} & {\hspace{0.5em}0.68012} & {\hspace{0.5em}0.67989} & {\hspace{0.5em}0.69827} & {\hspace{0.5em}0.71558} \\
\bottomrule
\end{talltblr}

}

\end{table}%

\subsection{Table 1}\label{table-1}

Table 1 shows tightness as the largest correlate in standardized
magnitude, followed by bachelor's share. STEM share and patents per
employee are positive but smaller, and manufacturing is reliably
negative relative to ICT.

\begin{table}[H]

\caption{\label{tbl-table2}Replication of Table 2 from Andreadis et
al.~(2025) - The Correlates of the Percentage Point Change in the Share
of AI Jobs}

\centering{

\centering
\begin{talltblr}[         %% tabularray outer open
entry=none,label=none,
note{}={This table examines the demographic, innovation, and industry determinants of the percentage point change in AI job share between two pooled periods: 2017-2018 and 2022-2023. The dependent variable measures the change in AI intensity (multiplied by 100 to express in percentage points), capturing dynamic shifts rather than static levels. All explanatory variables are measured in 2017 (before the growth period) and standardized as z-scores. The sample includes 2,473 counties with sufficient data across both periods. All coefficients represent percentage point changes in the growth of AI job share for a one standard deviation increase in the 2017 explanatory variable. Models are estimated using ordinary least squares with no fixed effects (columns 1-4) or state fixed effects (column 5). Standard errors are clustered at the county level. },
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]Q[]Q[]Q[]Q[]},
column{2}={si={table-format=-1.5,table-align-text-before=false,table-align-text-after=false,input-symbols={-,\*+()}},},
cell{1}{2}={guard,halign=c,},
column{3}={si={table-format=-1.5,table-align-text-before=false,table-align-text-after=false,input-symbols={-,\*+()}},},
cell{1}{3}={guard,halign=c,},
column{4}={si={table-format=-1.5,table-align-text-before=false,table-align-text-after=false,input-symbols={-,\*+()}},},
cell{1}{4}={guard,halign=c,},
column{5}={si={table-format=-1.5,table-align-text-before=false,table-align-text-after=false,input-symbols={-,\*+()}},},
cell{1}{5}={guard,halign=c,},
column{6}={si={table-format=-1.5,table-align-text-before=false,table-align-text-after=false,input-symbols={-,\*+()}},},
cell{1}{6}={guard,halign=c,},
column{1}={}{halign=l,},
}                     %% tabularray inner close
\toprule
& (1) & (2) & (3) & (4) & (5) \\ \midrule %% TinyTableHeader
Bachelors Share & 0.0124 &  &  & -0.0487 & -0.0457 \\
& (0.0267) &  &  & (0.0313) & (0.0330) \\
Income, Log & 0.0832 &  &  & 0.0748 & 0.0565 \\
& (0.0456) &  &  & (0.0472) & (0.0552) \\
Tightness & 0.1426 &  &  & 0.1571 & 0.1446 \\
& (0.0444) &  &  & (0.0526) & (0.0591) \\
Stem Degrees' share &  & 0.0794 &  & 0.0600 & 0.0513 \\
&  & (0.0203) &  & (0.0232) & (0.0224) \\
Large Firms &  &  & 0.0400 & -0.0237 & -0.0181 \\
&  &  & (0.0188) & (0.0240) & (0.0252) \\
ICT sector Intensity &  &  & 0.0339 & 0.0043 & 0.0176 \\
&  &  & (0.0205) & (0.0226) & (0.0229) \\
Manufacturing &  &  & -0.0685 & -0.0372 & -0.0185 \\
&  &  & (0.0195) & (0.0216) & (0.0237) \\
Turnover Rate &  &  & -0.0414 & -0.0240 & -0.0215 \\
&  &  & (0.0262) & (0.0291) & (0.0319) \\
Fixed effects & {\hspace{0.5em}None} & {\hspace{0.5em}None} & {\hspace{0.5em}None} & {\hspace{0.5em}None} & {\hspace{0.5em}State} \\
Observations & {\hspace{0.5em}2,029} & {\hspace{0.5em}2,029} & {\hspace{0.5em}2,029} & {\hspace{0.5em}2,029} & {\hspace{0.5em}2,029} \\
R² & {\hspace{0.5em}0.0231} & {\hspace{0.5em}0.0191} & {\hspace{0.5em}0.0151} & {\hspace{0.5em}0.0345} & {\hspace{0.5em}0.0938} \\
\bottomrule
\end{talltblr}

}

\end{table}%

\subsection{Table 2}\label{table-2}

In the growth specification, tightness and STEM degree share are among
the largest positive correlates, while several industry variables are
small and imprecise. Table 2 reports a cleaned replication that removes
redundant steps and intermediate overwrites while preserving the
published specification and sample construction. For transparency, the
as-provided replication (including the intermediate overwrite in the
posted script and the missing immigration series) is reported in
Appendix A.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{replication_files/figure-pdf/fig-map-1.pdf}}

}

\caption{\label{fig-map}Spatial heterogeneity in AI job share across US
counties. Panel A shows the average share of AI-related job postings
from 2014 to 2023. Panel B shows percentage-point changes between 2018
and 2023. Connecticut has no county observations in the provided
dataset, so it is shown as no data.}

\end{figure}%

\section{The Problem of Denominator
Contamination}\label{the-problem-of-denominator-contamination}

Consider a gym that reports the share of protein smoothies among all
drinks sold and a separate measure of ``thirstiness'' defined as total
drinks sold divided by the number of gym members. Even if smoothie
orders are unrelated to membership, the shared total-drinks term
mechanically links the two ratios. Counties face the same arithmetic: AI
intensity divides AI postings by total postings, while tightness divides
total postings by unemployment. The shared denominator can create
correlation even absent a causal link between the underlying economic
quantities.

Let AI intensity be (A/T) and tightness be (T/U), where (A) is AI
postings, (T) is total postings, and (U) is unemployment. The shared (T)
term can induce mechanical correlation, but the magnitude and sign
depend on the data-generating process and on how ratio variability
interacts with (T). This motivates the simulation below, which shows
that the contaminated specification can produce nonzero coefficients
even when the AI rate is generated independently of unemployment. In
that setting, tightness should be interpreted as a partial correlation
with a mechanical component rather than a causal effect.

\subsection{Simulation}\label{simulation}

We calibrate the simulation to match the empirical distributions of
total postings and unemployment in the data. We generate AI postings
independently of total postings and unemployment (matched to the
empirical AI-postings distribution), and then construct AI intensity by
dividing by total postings. This keeps the mechanical illustration close
to the scale and dispersion observed in the county-year panel while
ensuring that any correlation between AI intensity and tightness is
driven by shared construction rather than an imposed relationship. The
sign and magnitude of the mechanical component depend on the
distributions of the shared denominator and the regressor. The
simulation isolates the mechanical component by generating AI postings
and unemployment independently, then showing that the contaminated
regressor still loads nontrivially because T appears in both constructed
variables.

\begin{figure}[H]

\caption{\label{fig-simulation}Simulation: Mechanical correlation from
denominator contamination. AI postings are generated independently of
total postings and unemployment (matched to the empirical AI-postings
distribution). Contaminated tightness uses the same total postings as
the AI intensity denominator (T/U), while the clean proxy uses an
independent postings draw (T*/U).}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{replication_files/figure-pdf/fig-simulation-1.pdf}}

}

\end{figure}%

\begin{longtable}[]{@{}lcc@{}}

\caption{\label{tbl-simulation}}

\tabularnewline

\toprule\noalign{}
Specification & Mean & 95\% CI \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Contaminated tightness & -2.8438 & {[}-5.5878, -0.6736{]} \\
Uncontaminated tightness & 0.0870 & {[}-3.3021, 5.1185{]} \\

\end{longtable}

\begin{figure}[H]

\caption{\label{fig-diagnostic-scatter}Diagnostic scatter: total
postings vs.~AI intensity and tightness (clipped at 99th percentile;
loess smoother shown)}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{replication_files/figure-pdf/fig-diagnostic-scatter-1.pdf}}

}

\end{figure}%

The diagnostic scatter shows strong dependence on total postings in both
series, consistent with a shared arithmetic component. \emph{Notes:}
Simulation calibrated to the empirical distributions of postings and
unemployment. AI postings are generated independently of total postings
and unemployment (matched to the empirical AI-postings distribution),
and AI intensity is constructed by dividing by total postings. The
contaminated specification produces a mechanical coefficient of
approximately -2.844 (95\% CI {[}-5.588, -0.674{]}) even under this
independence (2,000 replications). The uncontaminated specification is
near zero (0.087).

To preserve the economic meaning of tightness while isolating the
problematic component, we report three complementary checks: (i)
omitting tightness, (ii) decomposing tightness into log(postings) and
log(unemployment) and residualizing tightness on those components, and
(iii) a count model with a postings offset.

\subsection{Reanalysis Excluding Tightness (Table 1, Column
4)}\label{reanalysis-excluding-tightness-table-1-column-4}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.3200}}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.3067}}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2400}}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1333}}@{}}

\caption{\label{tbl-no-tightness-t1}}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Baseline (replicated)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
No Tightness
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
\% Change
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Bachelor's share & 0.1817 (0.0505) & 0.2512 (0.0503) & +38\% \\
House price growth & -0.0142 (0.0079) & -0.0167 (0.0081) & +18\% \\
Patents per employee & 0.0295 (0.0113) & 0.0272 (0.0100) & -8\% \\
STEM degrees share & 0.0475 (0.0205) & 0.0585 (0.0224) & +23\% \\
ICT sector intensity & 0.0258 (0.0135) & 0.0173 (0.0140) & -33\% \\
Manufacturing intensity & -0.0333 (0.0108) & -0.0453 (0.0111) & +36\% \\
Turnover rate & 0.0188 (0.0137) & 0.0345 (0.0136) & +83\% \\

\end{longtable}

\emph{Notes:} This table compares Table 1's baseline specification
(column 4) to the same model estimated without labor-market tightness.

\subsection{Reanalysis Excluding Tightness (Table 2, Column
4)}\label{reanalysis-excluding-tightness-table-2-column-4}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.3200}}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.3067}}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2400}}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1333}}@{}}

\caption{\label{tbl-no-tightness-t2}}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Baseline (replicated)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
No Tightness
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
\% Change
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Bachelor's share & -0.0322 (0.0272) & 0.0039 (0.0261) & -112\% \\
House price growth & -0.0135 (0.0194) & -0.0097 (0.0193) & -28\% \\
Patents per employee & -0.0139 (0.0118) & -0.0104 (0.0117) & -25\% \\
STEM degrees share & 0.0539 (0.0204) & 0.0531 (0.0204) & -1\% \\
ICT sector intensity & 0.0137 (0.0188) & 0.0232 (0.0191) & +70\% \\
Manufacturing intensity & -0.0128 (0.0173) & -0.0169 (0.0173) & +32\% \\
Turnover rate & -0.0419 (0.0231) & -0.0388 (0.0230) & -7\% \\

\end{longtable}

\emph{Notes:} This table compares Table 2's baseline specification
(column 4) to the same model estimated without labor-market tightness.

\subsection{Decomposing Tightness: Log(Postings) and
Log(Unemployment)}\label{decomposing-tightness-logpostings-and-logunemployment}

As a direct check on the contaminated regressor, we replace tightness
\(T/U\) with its components, \mbox{$\\log(T)$} and \mbox{$\\log(U)$}, in
the levels specification. This tests whether the tightness signal is
primarily loading on postings scale rather than unemployment.

\begin{longtable}[]{@{}lc@{}}

\caption{\label{tbl-tightness-decomp}}

\tabularnewline

\toprule\noalign{}
Term & Estimate \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Tightness (baseline) & 0.2765 (0.0585) \\
Log total postings & 0.4345 (0.0610) \\
Log unemployment & 0.0947 (0.0615) \\

\end{longtable}

\emph{Notes:} Decomposition uses the same controls and fixed effects as
Table 1, column 4.

\subsection{Empirical Decomposition: Residualized Tightness
(Levels)}\label{empirical-decomposition-residualized-tightness-levels}

To quantify how much of the tightness signal is tied to the postings
component in the empirical specification, we residualize tightness on
\mbox{$\\log(T)$} and \mbox{$\\log(U)$} using the same fixed effects and
weights, and then re-estimate the baseline model with the residualized
tightness. This keeps the original controls and weighting while removing
the variation in tightness that is mechanically aligned with postings
scale.

\begin{longtable}[]{@{}lc@{}}

\caption{\label{tbl-tightness-resid}}

\tabularnewline

\toprule\noalign{}
Term & Estimate \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Tightness (baseline) & 0.2765 (0.0585) \\
Tightness (residualized) & 0.3128 (0.0809) \\

\end{longtable}

\emph{Notes:} Residualization uses the same fixed effects and posting
weights as Table 1, column 4.

To quantify how much tightness is driven by postings scale in the
empirical specification, we compute the within-FE R² from the
residualization regression above. In this sample, log(postings) and
log(unemployment) explain 76.5\% of tightness variation.

\subsection{Tightness Horse Race
(Levels)}\label{tightness-horse-race-levels}

\begin{longtable}[]{@{}lc@{}}

\caption{\label{tbl-tightness-horserace}}

\tabularnewline

\toprule\noalign{}
Specification & Estimate \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Baseline: Tightness (T/U) & 0.2765 (0.0585) \\
Decomposition: log(T) & 0.4345 (0.0610) \\
Decomposition: log(U) & 0.0947 (0.0615) \\
Residualized Tightness & 0.3128 (0.0809) \\
Unemployment Rate Proxy & 0.0323 (0.0130) \\
Poisson Offset Model & 0.0034 (0.0195) \\

\end{longtable}

\emph{Notes:} All specifications use the full set of controls and
county/year fixed effects. The Poisson model uses a log(total postings)
offset.

\subsection{Count Model with Offset
(Levels)}\label{count-model-with-offset-levels}

As a second alternative, we model AI postings counts with an offset for
total postings. This specification avoids ratio outcomes while
preserving the scale of postings in the likelihood.

\begin{longtable}[]{@{}lc@{}}

\caption{\label{tbl-offset-poisson}}

\tabularnewline

\toprule\noalign{}
Model & Tightness \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
OLS ratio (Table 1, Col. 4) & 0.2765 (0.0585) \\
Poisson w/ offset & 0.0034 (0.0195) \\

\end{longtable}

\emph{Notes:} Offset is \mbox{$\\log(T)$}, where \(T\) is total
postings.

\subsection{Alternative Tightness Proxy: Unemployment
Rate}\label{alternative-tightness-proxy-unemployment-rate}

As a practical alternative that avoids sharing the postings denominator,
we replace tightness with the unemployment rate. This keeps the
labor-market dimension while removing the mechanical overlap with AI
intensity.

\begin{longtable}[]{@{}lcc@{}}

\caption{\label{tbl-unrate-proxy}}

\tabularnewline

\toprule\noalign{}
Outcome & Tightness & Unemployment.rate \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Table 1 (levels, col.~4) & 0.2765 (0.0585) & 0.0323 (0.0130) \\
Table 2 (growth, col.~4) & 0.0732 (0.0291) & -0.0249 (0.0190) \\

\end{longtable}

\emph{Notes:} Tightness and unemployment rate are both standardized. The
unemployment-rate proxy avoids the shared denominator with AI intensity
while retaining a labor-market signal.

\section{Conclusion}\label{conclusion}

Denominator contamination in labor-market tightness creates a mechanical
component in the estimated relationship. Because total postings appear
in both the AI-intensity denominator and the tightness numerator, the
tightness coefficient partly reflects shared arithmetic structure even
when the AI rate is generated independently of unemployment. The DAG and
simulation show that this component is not merely theoretical: under
this calibrated DGP, the contaminated specification yields a nonzero
mechanical coefficient, while the uncontaminated specification centers
near zero.

Re-estimating the main specification after removing tightness reduces
the magnitudes of the remaining correlates and weakens several
associations. As a secondary check, we compare alternative weighting
schemes after removing tightness; coefficients attenuate on average,
indicating sensitivity to how county-year relationships are aggregated.

These results do not overturn AKCLM's descriptive contribution, but they
suggest a more nuanced interpretation. The headline tightness result
partly reflects shared arithmetic structure, and the remaining
associations are more modest in magnitude once the contaminated variable
is removed and alternative weighting schemes are considered. Researchers
using similar ratio-based labor-market variables should avoid shared
components or explicitly test for mechanical correlation.

\section*{Bibliography}\label{bibliography}
\addcontentsline{toc}{section}{Bibliography}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-acemoglu2024}
\textbf{Acemoglu, D.} 2024. {``The simple macroeconomics of {AI}.''}
Working Paper. 32487. National Bureau of Economic Research DOI:
\href{https://doi.org/10.3386/w32487}{10.3386/w32487}.

\bibitem[\citeproctext]{ref-acemoglu2022}
\textbf{Acemoglu, D.}, \textbf{D. Autor}, \textbf{J. Hazell}, \textbf{P.
Restrepo}. 2022. {``Artificial intelligence and jobs: Evidence from
online vacancies.''} \emph{Journal of Labor Economics} 40(S1):
S293--S340. DOI: \href{https://doi.org/10.1086/718327}{10.1086/718327}.

\bibitem[\citeproctext]{ref-acemoglu2019}
\textbf{Acemoglu, D.}, \textbf{P. Restrepo}. 2019. {``Automation and new
tasks: How technology displaces and reinstates labor.''} \emph{Journal
of Economic Perspectives} 33(2): 3--30. DOI:
\href{https://doi.org/10.1257/jep.33.2.3}{10.1257/jep.33.2.3}.

\bibitem[\citeproctext]{ref-andreadis2025}
\textbf{Andreadis, L.}, \textbf{E. Kalotychou}, \textbf{M.
Chatzikonstantinou}, \textbf{C. Louca}, \textbf{C. A. Makridis}. 2025.
{``Local heterogeneity in artificial intelligence jobs over time and
space.''} \emph{AEA Papers and Proceedings} 115: 29--34. DOI:
\href{https://doi.org/10.1257/pandp.20251001}{10.1257/pandp.20251001}.

\bibitem[\citeproctext]{ref-angrist2009mostly}
\textbf{Angrist, J. D.}, \textbf{J.-S. Pischke}. 2009. \emph{Mostly
harmless econometrics: An empiricist's companion} Princeton, NJ:
Princeton University Press.

\bibitem[\citeproctext]{ref-modelsummary}
\textbf{Arel-Bundock, V.} 2022. {``{modelsummary}: Data and model
summaries in {R}.''} \emph{Journal of Statistical Software} 103(1):
1--23. DOI:
\href{https://doi.org/10.18637/jss.v103.i01}{10.18637/jss.v103.i01}.

\bibitem[\citeproctext]{ref-autor2015}
\textbf{Autor, D. H.} 2015. {``Why are there still so many jobs? The
history and future of workplace automation.''} \emph{Journal of Economic
Perspectives} 29(3): 3--30. DOI:
\href{https://doi.org/10.1257/jep.29.3.3}{10.1257/jep.29.3.3}.

\bibitem[\citeproctext]{ref-babina2024}
\textbf{Babina, T.}, \textbf{A. Fedyk}, \textbf{A. He}, \textbf{J.
Hodson}. 2024. {``Artificial intelligence, firm growth, and product
innovation.''} \emph{Journal of Financial Economics} 151(C): 103745.
DOI:
\href{https://doi.org/10.1016/j.jfineco.2023.103745}{10.1016/j.jfineco.2023.103745}.

\bibitem[\citeproctext]{ref-beckett2023}
\textbf{Beckett, E.} 2023. {``Demand for {AI} skills continues
climbing.''} Lightcast Blog. \url{https://lightcast.io/}.

\bibitem[\citeproctext]{ref-fixest}
\textbf{Bergé, L.} 2018. {``Efficient estimation of maximum likelihood
models with multiple fixed-effects: The {R} package {FENmlm}.''}
\emph{CREA Discussion Papers} (13).

\bibitem[\citeproctext]{ref-bogin2019}
\textbf{Bogin, A.}, \textbf{W. Doerner}, \textbf{W. Larson}. 2019.
{``Local house price dynamics: New indices and stylized facts.''}
\emph{Real Estate Economics} 47(2): 365--398. DOI:
\href{https://doi.org/10.1111/1540-6229.12233}{10.1111/1540-6229.12233}.

\bibitem[\citeproctext]{ref-brynjolfsson2021}
\textbf{Brynjolfsson, E.}, \textbf{D. Rock}, \textbf{C. Syverson}. 2021.
{``The productivity {J}-curve: How intangibles complement
general-purpose technologies.''} \emph{American Economic Journal:
Macroeconomics} 13(1): 333--372. DOI:
\href{https://doi.org/10.1257/mac.20180386}{10.1257/mac.20180386}.

\bibitem[\citeproctext]{ref-cinelli2022}
\textbf{Cinelli, C.}, \textbf{C. Hazlett}, \textbf{J. Ferwerda},
\textbf{J. Hainmueller}. 2022. {``Sensitivity analysis for omitted
variable bias.''} \emph{Journal of the Royal Statistical Society: Series
B}.

\bibitem[\citeproctext]{ref-cunningham2021causal}
\textbf{Cunningham, S.} 2021. \emph{Causal inference: The mixtape} New
Haven, CT: Yale University Press.

\bibitem[\citeproctext]{ref-usmap}
\textbf{Di Lorenzo, P.} 2024. \emph{Usmap: US maps including alaska and
hawaii} \url{https://CRAN.R-project.org/package=usmap}.

\bibitem[\citeproctext]{ref-eloundou2024}
\textbf{Eloundou, T.}, \textbf{S. Manning}, \textbf{P. Mishkin},
\textbf{D. Rock}. 2024. {``{GPTs} are {GPTs}: Labor market impact
potential of {LLMs}.''} \emph{Science} 384(6702): 1306--1308. DOI:
\href{https://doi.org/10.1126/science.adj0998}{10.1126/science.adj0998}.

\bibitem[\citeproctext]{ref-gibbons2015spatial}
\textbf{Gibbons, S.}, \textbf{H. G. Overman}, \textbf{E. Patacchini}.
2015. {``Spatial methods.''} \emph{Handbook of Regional and Urban
Economics} 5: 115--168.

\bibitem[\citeproctext]{ref-giczy2022}
\textbf{Giczy, A. V.}, \textbf{N. A. Pairolero}, \textbf{A. A. Toole}.
2022. {``Identifying artificial intelligence ({AI}) invention: A novel
{AI} patent dataset.''} \emph{The Journal of Technology Transfer} 47(2):
476--505. DOI:
\href{https://doi.org/10.1007/s10961-021-09900-2}{10.1007/s10961-021-09900-2}.

\bibitem[\citeproctext]{ref-holland1986}
\textbf{Holland, P. W.} 1986. {``Statistics and causal inference.''}
\emph{Journal of the American Statistical Association} 81(396):
945--960. DOI:
\href{https://doi.org/10.1080/01621459.1986.10478354}{10.1080/01621459.1986.10478354}.

\bibitem[\citeproctext]{ref-kline2014}
\textbf{Kline, P.}, \textbf{E. Moretti}. 2014. {``People, places, and
public policy: Some simple welfare economics of local economic
development programs.''} \emph{Annual Review of Economics} 6: 629--662.
DOI:
\href{https://doi.org/10.1146/annurev-economics-080213-041024}{10.1146/annurev-economics-080213-041024}.

\bibitem[\citeproctext]{ref-kronmal1993spurious}
\textbf{Kronmal, R. A.} 1993. {``Spurious correlation and the fallacy of
the ratio standard revisited.''} \emph{Journal of the Royal Statistical
Society: Series A (Statistics in Society)} 156(3): 379--392. DOI:
\href{https://doi.org/10.2307/2983064}{10.2307/2983064}.

\bibitem[\citeproctext]{ref-moretti2004}
\textbf{Moretti, E.} 2004. {``Estimating the social return to higher
education: Evidence from longitudinal and repeated cross-sectional
data.''} \emph{Journal of Econometrics} 121(1-2): 175--212. DOI:
\href{https://doi.org/10.1016/j.jeconom.2003.10.015}{10.1016/j.jeconom.2003.10.015}.

\bibitem[\citeproctext]{ref-RCoreTeam}
\textbf{R Core Team}. 2024. \emph{R: A language and environment for
statistical computing} Vienna, Austria: R Foundation for Statistical
Computing. \url{https://www.R-project.org/}.

\bibitem[\citeproctext]{ref-bls_laus}
\textbf{U.S. Bureau of Labor Statistics}. 2024. {``Local area
unemployment statistics ({LAUS}).''} \url{https://www.bls.gov/lau/}.

\bibitem[\citeproctext]{ref-census_acs}
\textbf{U.S. Census Bureau}. 2024a. {``American community survey ({ACS})
5-year data.''} Accessed July 1, 2024.
\url{https://www.census.gov/data/datasets/time-series/econ/acs/acs-datasets.html}.

\bibitem[\citeproctext]{ref-census_cbp}
\textbf{U.S. Census Bureau}. 2024b. {``County business patterns
({CBP}).''} Accessed July 1, 2024.
\url{https://www.census.gov/programs-surveys/cbp/data/datasets.html}.

\bibitem[\citeproctext]{ref-census_qwi}
\textbf{U.S. Census Bureau}. 2024c. {``Quarterly workforce indicators
({QWI}).''} LEHD Program; Accessed July 1, 2024.
\url{https://lehd.ces.census.gov/data/}.

\bibitem[\citeproctext]{ref-tidyverse}
\textbf{Wickham, H.}, \textbf{M. Averick}, \textbf{J. Bryan}, \textbf{W.
Chang}, \textbf{L. D. McGowan}, \textbf{R. François}, \textbf{G.
Grolemund}, et al. 2019. {``Welcome to the {Tidyverse}.''} \emph{Journal
of Open Source Software} 4(43): 1686. DOI:
\href{https://doi.org/10.21105/joss.01686}{10.21105/joss.01686}.

\bibitem[\citeproctext]{ref-wooldridge2005}
\textbf{Wooldridge, J. M.} 2005. {``Unobserved heterogeneity and
estimation of average partial effects.''} In \emph{Identification and
inference for econometric models: Essays in honor of thomas rothenberg},
Cambridge University Press.

\end{CSLReferences}

\newpage

\section*{Appendix A: Weighting
Sensitivity}\label{appendix-a-weighting-sensitivity}
\addcontentsline{toc}{section}{Appendix A: Weighting Sensitivity}

\subsection*{Log-Population Weights (Table 1, Column
4)}\label{log-population-weights-table-1-column-4}
\addcontentsline{toc}{subsection}{Log-Population Weights (Table 1,
Column 4)}

After removing the contaminated tightness variable, we test whether
remaining associations are sensitive to alternative aggregation schemes
by comparing unweighted, population-weighted, and
log-population-weighted estimates. Population weights correspond to a
person-weighted relationship; log(population) is an intermediate,
concave reweighting that tilts toward larger counties without letting a
few very large counties dominate. This provides a transparent
sensitivity check relative to the original posting-weighted estimand.
Coefficient magnitudes attenuate on average (see Figure 4).

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3077}}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3462}}
  >{\centering\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3462}}@{}}

\caption{\label{tbl-weights-robust}}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Scheme
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Table 1 median abs change
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Table 2 median abs change
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Unweighted & 21\% & 23\% \\
Population-weighted & 268\% & 135\% \\
Log-population weighted & 11\% & 5\% \\

\end{longtable}

\emph{Notes:} Median absolute changes are computed relative to the
no-tightness baseline with log(1+ads) weights.

\begin{figure}[H]

\caption{\label{fig-logpop-compact-t1}Coefficient sensitivity after
removing tightness using log-population weights (Table 1, Col. 4)}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{replication_files/figure-pdf/fig-logpop-compact-t1-1.pdf}}

}

\end{figure}%

Median absolute change across coefficients in Figure 4: 25\%.

\subsection*{Log-Population Weights (Table 2, Column
4)}\label{log-population-weights-table-2-column-4}
\addcontentsline{toc}{subsection}{Log-Population Weights (Table 2,
Column 4)}

We repeat the same exercise for the Table 2 baseline (column 4).
Coefficient magnitudes again attenuate under log(population) weights
(see Figure 5).

\begin{figure}[H]

\caption{\label{fig-logpop-compact-t2}Coefficient sensitivity after
removing tightness using log-population weights (Table 2, Col. 4)}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{replication_files/figure-pdf/fig-logpop-compact-t2-1.pdf}}

}

\end{figure}%

Median absolute change across coefficients in Figure 5: 27\%.




\end{document}
